language: node_js
node_js:
- '4.0'
- '9.0'
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    skip_cleanup: true
    email: tituswormer@gmail.com
    api_key:
      secure: A6+aTkwWeACZGO22dm+PedgUyhFk9LLMtiRdrLkTniDUEN/5r+x0evLkVG4z6p5wWnno3JrZ4HIVFqD7W+v+C/78WXmISSaLPxuBH8lZq64gmuBCmai0XpRByvpEdcwoqekn8ZdJFKGab126xo7VjpaUllPcjPEIR9Sx8QuJrGg=
    on:
      tags: true
      node: '9.0'
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: iaejkiZe2L6/WBi+OAlpGVN2EbFEc5/1rHBnuYmEb/70Q9cwuRvhLvtufphiBors6lV9r0JiezydYNlIB99ae0uIXKEYpYhqzVGaNKXfQ0BLrFHQMIbRMizfrecWAFOfP8njeyvE0TBWI8p54GEC0LwCfFNvzaHwPhcV1FI2JPc=
    file:
      - "retext-smartypants.js"
      - "retext-smartypants.min.js"
    on:
      tags: true
      node: '9.0'
